POST  http://localhost:3000/api/fotografos
Content-Type:  application/json

{
    "nombre": "fia",
    "apellidos":"Zamora",
    "direccion": "calle castellana 7",
    "email": "fia@gmail.com",
    "password": "holafia"
}


###


POST http://localhost:3000/api/fotografos/login_fotografo
Content-Type:  application/json

{
    "email": "fia@gmail.com",
    "password": "holafia"
}

###



GET http://localhost:3000/api/fotografos

###
PUT http://localhost:3000/api/fotografos/private
Content-Type:  application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb3RvZ3JhZm9JZCI6MjQsImNhZHVjYSI6MTYxNjU5MTU2MiwiaWF0IjoxNjE2NTg5NzYyfQ.1Hhnyx0ymaAc6t4yHhKsSvEAQxJMcwuMUi_9CJmzvao


{
    "id": 24,
    "nombre": "Zamora",
    "apellidos":"Campos de la Oliva",
    "direccion": "calle neolan",
    "email": "a@gmail.com",
    "password": "holabea"
}

###

DELETE http://localhost:3000/api/fotografos/private
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb3RvZ3JhZm9JZCI6MjUsImNhZHVjYSI6MTYxNjU5ODYxMywiaWF0IjoxNjE2NTk2ODEzfQ.U30rIaT6eYdTRKIbUfIwijyrzvG1JLla3ctK_L_QmW0





