GET http://localhost:3000/api/clientes

###

GET http://localhost:3000/api/clientes/private/perfil
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRlSWQiOjIwLCJjYWR1Y2EiOjE2MTY2MDI0MDUsImlhdCI6MTYxNjYwMDYwNX0.DdSUKheva_oROFsp4nUHd85yHPTgS-M2oDkeHEGSbKk

###

POST http://localhost:3000/api/clientes
Content-Type:  application/json

{
    "nombre": "ramon",
    "apellidos":"contreras",
    "direccion": "calle seis",
    "email": "ramon@gmail.com",
    "password": "1234"
}
###


POST http://localhost:3000/api/clientes/login_cliente
Content-Type:  application/json

{
    "email": "rosario@gmail.com",
    "password": "1234"
}

###

PUT http://localhost:3000/api/clientes/private
Content-Type:  application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRlSWQiOjE5LCJjYWR1Y2EiOjE2MTY2MDIxNDAsImlhdCI6MTYxNjYwMDM0MH0.swHxuDScd1RZ-AU0LtyJgrRnmIHIzSpwXiG_y5TNLVs


{
    "nombre": "rosa",
    "apellidos":"contreras",
    "direccion": "calle seis",
    "email": "rosario@gmail.com",
    "password": "1234"
}


###

DELETE http://localhost:3000/api/clientes/private
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRlSWQiOjE5LCJjYWR1Y2EiOjE2MTY2MDIxNDAsImlhdCI6MTYxNjYwMDM0MH0.swHxuDScd1RZ-AU0LtyJgrRnmIHIzSpwXiG_y5TNLVs
