POST  http://localhost:3000/fotografos
Content-Type:  application/json

{
    "nombre": "Pepe",
    "apellidos":"Calle",
    "direccion": "calle gran via 7",
    "email": "pepe@gmail.com",
    "password": "holaignacio"
}


###

POST http://localhost:3000/fotografos/login_fotografo
Content-Type:  application/json

{
    "email": "pepe@gmail.com",
    "password": "holaignacio"
}

###



GET http://localhost:3000/fotografos

###
PUT http://localhost:3000/fotografos
Content-Type:  application/json

{
    "id": 5,
    "nombre": "Update",
    "apellidos":"update",
    "direccion": "calle gran via 7",
    "email": "ignacio@gmail.com",
    "password": "holaignacio"
}

###

DELETE http://localhost:3000/fotografos/5 


