GET http://localhost:3000/api/clientes

###

GET http://localhost:3000/api/clientes/private/perfil

###

GET http://localhost:3000/api/clientes/private/favoritos
Content-Type:  application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRlSWQiOjI1LCJjYWR1Y2EiOjE2MTcxMDQ2MzcsImlhdCI6MTYxNzEwMjgzN30.gyo3a1jEolJO5AGAKHTM2-3vMdQhUmqdLnxgatyrBvE


###

POST http://localhost:3000/api/clientes
Content-Type:  application/json

{
    "nombre": "Maria",
    "apellidos":"lopez",
    "direccion": "calle seis",
    "email": "maria@gmail.com",
    "password": "Maria1234"
}
###


POST http://localhost:3000/api/clientes/login_cliente
Content-Type:  application/json

{
    "email": "bea127@gmail.com",
    "password": "Bea127"
}

###
POST http://localhost:3000/api/clientes/private/favoritos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRlSWQiOjI0LCJjYWR1Y2EiOjE2MTcxMDE3MTQsImlhdCI6MTYxNzA5OTkxNH0.OJ7QIJkSNqT-aETMP3ec38SgyDZu5i1QWZXLh48clvg
Content-Type:  application/json


{
    "fk_fotografo": 14
}





###

PUT http://localhost:3000/api/clientes/private
Content-Type:  application/json



{
    "nombre": "rosa",
    "apellidos":"contreras",
    "direccion": "calle seis",
    "email": "rosario@gmail.com",
    "password": "1234"
}


###
PATCH  http://localhost:3000/api/clientes/private
Content-Type:  application/json


{
    "id": 18,
    "password": "Beacampos1234"
}


###

DELETE http://localhost:3000/api/clientes/private

